### ISSUE TITLE
CUDA OOM issue

### ISSUE THREAD

**Issue by Shujian2015** [freewym/espresso#9]
Hi, I was running the Libri example and got CUDA OOM issue (either 1 or 4 v100 GPU). I tried `the --empty-cache-freq` flag. It still occurs OOM eventually although it takes longer to OOM.

Has anyone seen the same issue?

My setup: centos 7.5 | cuda 9.2 | python 3.6 | pytorch 1.3.0 | nccl 2.4.6

**Comment by freewym** [comment]
I have no experience with V100 GPUs. Does reducing `--max-tokens`  or `--max-sentences` help?

**Comment by Shujian2015** [comment]
Hi @freewym, thank for your quick response. I tried to reduce `--max-sentences` and it took more iteration to oom. Seems CUDA memory usage grows slowly over iterations even with `torch.cuda.empty_cache()`.

**Comment by Shujian2015** [comment]
I saw someone mentioned in Fairseq repo that downgrading cuda from 9.2 to 9.0 may help. Could you tell me what cuda and pytorch version did you use?

**Comment by freewym** [comment]
You could try --max-tokens since it's a more direct constraint to control memory usage.

Here is my environment:

Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Debian GNU/Linux 9.4 (stretch)
GCC version: (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
CMake version: version 3.7.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti

Nvidia driver version: 387.26
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.12.1
[conda] blas 1.0 mkl
[conda] mkl 2019.1 144
[conda] mkl-service 1.1.2 py37h90e4bf4_5
[conda] mkl_fft 1.0.10 py37ha843d7b_0
[conda] mkl_random 1.0.2 py37hd81dba3_0
[conda] pytorch 1.1.0 py3.7_cuda9.0.176_cudnn7.5.1_0 pytorch
[conda] torchvision 0.3.0 py37_cu9.0.176_1 pytorch

**Comment by Shujian2015** [comment]
Thanks again @freewym . 
`--max-tokens` didn't solve my problem but your config helps: cuda 9.0 + pytorch 1.1.0 + python 3.7. Peak GPU memory usage is constant so far.
